import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Switch from '@mui/material/Switch';
import ArrowBackIosNewIcon from '@mui/icons-material/ArrowBackIosNew';
import Link from 'next/link';
import { useAppDispatch, useAppSelector } from '@/store/hook';
import { useEffect } from 'react';
import { showLoading } from '@/store/loading/loadingSlice';

const Home: NextPage = () => {
  const loadingSlice = useAppSelector((state) => state.loadingSlice.isLoading);
  const dispatch = useAppDispatch();

  useEffect(() => {
    // dispatch(showLoading());
  }, [dispatch]);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Switch disabled defaultChecked />
      <ArrowBackIosNewIcon />
      <Link href={'/hung'}>Link hung</Link>
    </div>
  );
};

export default Home;
